chairs:
  - ACACIA_STAIRS
  - ANDESITE_STAIRS
  - BIRCH_STAIRS
  - BLACKSTONE_STAIRS
  - BRICK_STAIRS
  - COBBLESTONE_STAIRS
  - CRIMSON_STAIRS
  - DRAKOAK_STAIRS
  - DARK_PRISMARINE_STAIRS
  - DIORITE_STAIRS
  - END_STONE_STAIRS
  - GRANITE_STAIRS
  - JUNGLE_STAIRS