chairs:
- ACACIA_STAIRS
- ANDESITE_STAIRS
- BIRCH_STAIRS
- BLACKSTONE_STAIRS
- BRICK_STAIRS
- COBBLESTONE_STAIRS
- CRIMSON_STAIRS
- DRAKOAK_STAIRS
- DARK_PRISMARINE_STAIRS
- DIORITE_STAIRS
- END_STONE_STAIRS
- GRANITE_STAIRS
- JUNGLE_STAIRS
- PURPUR_STAIRS
- OAK_STAIRS
- STONE_BRICK_STAIRS
- NETHER_BRICK_STAIRS
- SANDSTONE_STAIRS
- SPRUCE_STAIRS
- WARPED_STAIRS
- QUARTZ_STAIRS
- DARK_OAK_STAIRS
- PRISMARINE_STAIRS
- PRISMARINE_BRICK_STAIRS
- RED_SANDSTONE_STAIRS
- POLISHED_GRANITE_STAIRS
- SMOOTH_RED_SANDSTONE_STAIRS
- MOSSY_STONE_BRICK_STAIRS
- POLISHED_DIORITE_STAIRS
- MOSSY_COBBLESTONE_STAIRS
- END_STONE_BRICK_STAIRS
- STONE_STAIRS
- SMOOTH_SANDSTONE_STAIRS
- SMOOTH_QUARTZ_STAIRS
- RED_NETHER_BRICK_STAIRS
- POLISHED_ANDESITE_STAIRS
- POLISHED_BLACKSTONE_STAIRS
- POLISHED_BLACKSTONE_BRICK_STAIRS